server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.10.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.10.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.leyou.user.pojo
